spring:
  application:
    name: courtier-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/courtier
    username: ${DB_USERNAME:courtier}
    password: ${DB_PASSWORD:courtier}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

server:
  port: 8080

courtier:
  jwt:
    secret: TWF5YmVTb21lZGF5RXZlcnl0aGluZ1dpbGxCZUZpbmU=
    access-token-expiry-ms: 3600000
    refresh-token-expiry-ms: 604800000